### ISSUE TITLE
Documentation issue, matchMedia should be ngMediaMatch

### ISSUE THREAD

**Issue by alanquigley** [jacopotarantino/angular-match-media#12]
Could be confusing.

**Comment by alanquigley** [comment]
Sorry, thats a bower issue, bower install angular-match-media installs https://github.com/IlanFrumer/angular-match-media

**Comment by jacopotarantino** [comment]
@alanquigley yeah haha. Sorry for that. Getting the package manager namespace you want for a project is getting harder and harder these days.

**Comment by jacopotarantino** [comment]
Hope the plugin helps, btw. Let me know if you have questions or leave a note so I can see where it's being used :)
