### ISSUE TITLE
Incorrect version number in match-media.js comment

### ISSUE THREAD

**Issue by hyronymus** [jacopotarantino/angular-match-media#13]
Hi, it looks like you have an old version number in the comment for the latest release.

**Comment by jacopotarantino** [comment]
Sorry, I'm not sure which comment you're talking about. I checked the tag and the bower.json file and they look fine to me. Is it somewhere else?

**Comment by bitflower** [comment]
This is fixed in Version 0.4.1.

I changed it when adding the last feature.

**Comment by jacopotarantino** [comment]
Oh good :)
