### ISSUE TITLE
screenSize.rules  customization on config() step

### ISSUE THREAD

**Issue by js-padavan** [jacopotarantino/angular-match-media#21]
It would be great if 'screenSize' service would be implemented as provider with methods for customization 'rules' object, thus it would be very convenient to define all custom rules on the app configuration step

**Comment by jacopotarantino** [comment]
While it's not currently possible to do this at the global level with a provider, you can set custom rules on any given instance of `screenSize`. See a demo [here](https://github.com/jacopotarantino/angular-match-media#custom-screen-sizes-or-media-queries). I'm going to close this as resolved but feel free to re-open or submit a PR if you'd still like it done with a provider
