### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by jpmnteiro** [jacopotarantino/angular-match-media#30]
Hi,

I've created the necessary TypeScript typings for your module. The pull request on DefinitelyTyped can be found [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8759). Hopefully it'll be merged soon.

Proper credit was given, but do check if there's anything you'd like to change.

**Comment by jacopotarantino** [comment]
Oh that's awesome! Thank you!
