### ISSUE TITLE
Could you release the latest version on npm?

### ISSUE THREAD

**Issue by kennynaoh** [jacopotarantino/angular-match-media#36]
Hello @jacopotarantino ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But I need some help.
Because I saw the latest version on [github](https://github.com/jacopotarantino/angular-match-media/tree/0.6.0) is v0.6.0, the latest version on [npm](https://www.npmjs.com/package/angular-media-queries) is v0.5.1.
Could you help me release the latest version on npm?
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8629

**Comment by jacopotarantino** [comment]
Thanks for the request and sorry for the delay. Version 0.6.1 (mostly just to avoid trying to "fix" some errant old tags) is now available on npm and github. If you can, comment back when it's up on cdnjs. Thanks again!

**Comment by kennynaoh** [comment]
Thanks!
