### ISSUE TITLE
Can't extend default rules

### ISSUE THREAD

**Issue by arajay** [jacopotarantino/angular-match-media#40]
The var defaultRules can't be extended. When I create my own rules, I have to redeclare all the default rules too. This could cause problems if the default breakpoints change in a later version.

Example
screenSize.rules = {
    lg: '(min-width: 1200px)', // default rule
    md: '(min-width: 992px) and (max-width: 1199px)', // default rule
    mobileLandscape: '(max-width: 768px) and (orientation: landscape)', // my custom rule
    sm: '(min-width: 768px) and (max-width: 991px)', // default rule
    xs: '(max-width: 767px)' // default rule
}

**Comment by jacopotarantino** [comment]
That seems quite true. Could you make a PR to fix it? Or better, a PR with a cleaned-up ng2 friendly API? It's a big ask but I don't have time to do the whole thing myself right now.

**Comment by zacronos** [comment]
This has been fixed on master.  (Next time a new npm version is published, this will be included.)

See the README for details on how to extend the default rules.
