### ISSUE TITLE
onRuleChange() is not available in version 0.6.1 listed on npmjs.com

### ISSUE THREAD

**Issue by bertysentry** [jacopotarantino/angular-match-media#47]
Hi,

This is a great library for AngularJS and thank you for all the effort you put into this project.

Can we please ask you a favor? Release the latest on npm. The *onRuleChange()* method is not available in the 0.6.1 package listed on npmjs.com (https://www.npmjs.com/package/angular-media-queries), which is shame as it's a **very** practical function.

Thank you!

**Comment by jacopotarantino** [comment]
i'm sorry but this repository is no longer maintained as angular@2 has been out for a while and really i just don't have the time for maintenance. if you'd like to use that particular version you can point your package.json to a specific commit or a fork if you need to. i'm also happy to share maintenance credentials.

**Comment by bertysentry** [comment]
Thank you @jacopotarantino , that's what I did (point to a specific commit). If there are other changes required, I'll submit a PR.
Also: while Angular 2+ has been out there for a while, it does not quite replace AngularJS, which many people still prefer over Angular2 ;-)

**Comment by jacopotarantino** [comment]
hehe. understood. very incidentally: have you looked at vuejs? i view it as a more modern ng1. it has a more similar API unlike ng2 which feels more like a radical departure from ng1.

**Comment by bertysentry** [comment]
Agreed on vue.js, much more lovable than ng2, imho...
