### ISSUE TITLE
Possible PR?

### ISSUE THREAD

**Issue by bensurman** [jacopotarantino/angular-match-media#9]
Hi, I was planning on making some improvements and submitting a PR, but once I started looking into the performance, and started thinking of new features I wanted, I ended up rewriting the entire code. 

Subsequently I have no idea if I changed too much to make a PR, so I uploaded it to its own repository instead for now. I have zero experience publishing on Github so I'm not sure what the best way forward from here is?  Should I still submit a PR?

If you want to check out what I've done it's at https://github.com/bensurman/angular-screenmatch

**Comment by jacopotarantino** [comment]
Haha. A programmer after my own heart. I have a bad habit of doing that as well. Definitely submit a PR. We can go over the code changes and I'll add you as a contributor.

**Comment by jacopotarantino** [comment]
Closing as the PR was closed due to age/ being too difficult to QA. I'd really like to collaborate on this though. Please let me know if you'd like to pair or something.
